# dbt/dbt_project.yml

name: 'my_portfolio'
version: '1.0.0'
config-version: 2

# ここで「どの接続設定(profiles.ymlの項目)」を使うか一回だけ指定
profile: 'my_portfolio_project'

# モデル（SQLファイル）を探すディレクトリ
model-paths: ["models"]
test-paths: ["tests"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# モデルの実行設定
models:
  my_portfolio:
    materialized: view
    staging:
      materialized: view
    marts:
      materialized: table
