# dbt/models/schema.yml
version: 2

sources:
  - name: raw_api
    # 環境変数からプロジェクトIDを読み込むように変更
    database: "{{ env_var('GCP_PROJECT_ID') }}" 
    schema: portfolio_dataset
    tables:
      - name: raw_data
        columns:
          - name: id
            tests:
              - not_null
              - unique
          - name: encrypted_content
            tests:
              - not_null
