name: 'End-to-End Data Pipeline'

on:
  push:
    branches: [ "main" ] # mainブランチへのpushで起動

jobs:
  pipeline:
    runs-on: ubuntu-latest
    
    # 全ステップで共通して使う環境変数
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }} # Terraform用
      GCP_SA_KEY_JSON: ${{ secrets.GCP_SA_KEY }}    # dbt用
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      AES_ENCRYPT_KEY: ${{ secrets.AES_ENCRYPT_KEY }}
      BQ_DATASET_ID: "api_encrypted_store"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

     ####################################################
      # --- 1. インフラ構築 (Terraform) ---
     ####################################################
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        
     ####################################################
      - name: Terraform Init & Apply
     ####################################################

        run: |
          # 1. 鍵ファイルを一時的に作成
          echo '${{ secrets.GCP_SA_KEY }}' > gcp-key.json
          export GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/gcp-key.json
          
          # 2. 実行
          terraform init
          terraform apply -auto-approve -var="project_id=${{ env.GCP_PROJECT_ID }}"
          
          # 3. 終わったら鍵ファイルを削除（セキュリティのため）
          rm gcp-key.json
        working-directory: ./terraform

     ####################################################
      # --- 2. Python 環境構築 & テスト (pytest) ---
     ####################################################
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest dbt-bigquery

      # --- 2.5 テストの実行 (ここを追加！) ---
      - name: Run Pytest
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pytest tests/

      # --- 3. データ取得・暗号化・ロード (Python) ---
      - name: Run Python Script
        run: |
          # 1. 鍵ファイルを一時的に作成
          echo '${{ secrets.GCP_SA_KEY }}' > gcp-key.json
          export GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/gcp-key.json
          
          # 2. 実行
          python src/main.py
          
          # 3. 終わったら鍵ファイルを削除
          rm gcp-key.json
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          AES_ENCRYPT_KEY: ${{ secrets.AES_ENCRYPT_KEY }}
          BQ_DATASET_ID: "api_encrypted_store"

      # --- 4. データ変換・品質チェック (dbt) ---
      - name: Run dbt
        run: |
          # dbtも同様に鍵ファイルが必要
          echo '${{ secrets.GCP_SA_KEY }}' > gcp-key.json
          export GCP_SA_KEY_JSON=$(pwd)/gcp-key.json
          
          dbt deps
          dbt run
          dbt test
          
          rm gcp-key.json
        working-directory: ./dbt
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          BQ_DATASET_ID: "api_encrypted_store"
          DBT_PROFILES_DIR: "."
